### ISSUE TITLE
[Bug]: All but one recipe from the stonecutter is completely gone for each type of stone

### ISSUE THREAD

**Issue by Lynoph** [someaddons/recipeessentials#1] opened 2023-09-06 00:22 UTC
### Describe the bug you're experiencing

After adding this mod all recipes from the stonecutter are removed except for one, this recipe varies depending on the type of stone you put in it. For example, when putting cobblestone the only available recipe is the cobblestone wall.
Ideally all recipes should be visible including modded ones.
I decided to test this with no mod other than this one and cupboard to make sure and the bug behaves a little bit different but it seems to be overall the same. When placing stone in the stonecutter the only recipe seems to be stone bricks stairs but the result on the right shows as chiseled stone bricks, if clicked again it changes into the stone bricks stairs and this way you can get only either of these two results.
I've linked the latest log for the not modded test.

### Reproducability

- Install the mod
- Create a new world or log into an already existing one
- Attempt to use the stonecutter with any type of stone

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/Lynoph/b78c2047703eb8e17a3781134e4aa6d4

**Comment by someaddons** [comment] 2023-09-06 06:53
which recipe essentials version are you using? cant seem to reproduce on the newest

**Comment by Lynoph** [comment] 2023-09-06 07:32
I'm using the newest version, recipeessentials-1.19.2-1.9
It's worth noting that this has been an issue since the first release version. If it helps my Forge version is 43.2.13, just now thought about that as a possible factor.
Edit: Just tested it on the latest Forge version and it still happens.

**Comment by someaddons** [comment] 2023-09-06 09:04
![image](https://github.com/someaddons/recipeessentials/assets/38401808/4a828b5a-094b-4e4b-9771-823528d1ff8d)

I launched with just 1.9 recipe essentials and forge 43.2.23

Could you check the mod folder to make sure its actually loading 1.9? If so could you tell me your exact reproduction steps? Do X then Y then Z?

**Comment by Lynoph** [comment] 2023-09-06 21:21
Yeah i made sure to try this without any other mod other than cupboard and it was with the 1.9 version of recipe essentials.
As for the reproduction steps i tried both in an already existing world and creating a new world then going towards the stonecutter (or placing one from the creative inventory) and trying it out with Stone, Cobbled Deepslate, Granite, Diorite, Andesite, Cobblestone. All of those just showed a single recipe.
I will keep trying and see if i can find any other possible factor and keep you updated.

**Comment by someaddons** [comment] 2023-09-06 21:46
very odd since we should be both trying the same thing :D could you just zip and send me your testing instance? on google drive or dropbox orso

**Comment by Lynoph** [comment] 2023-09-06 21:51
![2023-09-06_16 48 37](https://github.com/someaddons/recipeessentials/assets/144184258/0459f9d2-4b3a-4927-8614-33458e892410)
Here is a screenshot of the bug in a brand new world with only cupboard and recipeessentials.
I'll make a drive real quick!

**Comment by Lynoph** [comment] 2023-09-06 21:59
https://drive.google.com/drive/folders/1wViju51atsXeCUG1SWh5t8zc6tOf5jO6?usp=sharing
Is this good? Let me know if i'm missing something here.

**Comment by someaddons** [comment] 2023-09-06 22:08
![image](https://github.com/someaddons/recipeessentials/assets/38401808/8192fc60-47af-4244-8294-e4c69d9ca932)
works just fine xD

**Comment by someaddons** [comment] 2023-09-06 22:08
maybe an odd launcher bug where its using a different folder/instance than one would expect?

**Comment by Lynoph** [comment] 2023-09-06 22:10
I am so confused i have no idea how this is happening lmao. You can see in the screenshot i sent that's basically what i see lol

Hmm i wonder, i basically only use the Minecraft launcher and only the Minecraft launcher every time i play the game. I don't use the CF one or any other launcher and i've never even used those before either so there are no potential files for them.

**Comment by someaddons** [comment] 2023-09-06 22:11
I'm usually using cf launcher or prism or gdllauncher those all work fine xD

**Comment by Lynoph** [comment] 2023-09-06 22:19
Yeah i'm not really sure what the issue is at this point lmao. I tried deleting all my settings and stuff and it still happens.
I think i'm gonna have to give up on this one honestly. Thanks for the help, at least we now know it's most likely a me issue somehow.

**Comment by someaddons** [comment] 2023-09-06 22:21
ye I suspect there is some hidden minecraft folder it uses which has like an older 1.7 version 🤷

**Comment by Lynoph** [comment] 2023-09-06 22:24
It's really strange since it works just fine if i remove the mod.

**Comment by someaddons** [comment] 2023-09-07 09:31
are you maybe loading some datapacks you didnt send me?

**Comment by Lynoph** [comment] 2023-09-07 20:23
Shouldn't be the case, i load my datapacks through Paxi and even after removing it i also made sure to remove pretty much anything that can be removed from my instance. I even removed the resourcepacks, every config file i had and my options.txt as well :(
Made sure everything was as clean as possible when i did the only recipeessentials test.

**Comment by KlaraChaos** [comment] 2023-09-13 01:10
hello comming in here saying i have the same issue!
playing better mc forge version on the newest version of mc and the mod 
![IMG_4513](https://github.com/someaddons/recipeessentials/assets/75270975/cf36eb90-8627-43d9-9ace-11166b7cf3e7)

tho for me its stone shingels (most likly due to stoneworks

**Comment by someaddons** [comment] 2023-09-13 11:43
> Yeah i'm not really sure what the issue is at this point lmao. I tried deleting all my settings and stuff and it still happens. I think i'm gonna have to give up on this one honestly. Thanks for the help, at least we now know it's most likely a me issue somehow.

Could you maybe make a video of your reproduction steps? that might help, starting from game launch -> issue occurs

**Comment by Lynoph** [comment] 2023-09-15 01:00
Sorry i just saw this, good news tho
Latest version seems to have fixed the issue now. Thanks!

**Comment by someaddons** [comment] 2023-09-15 07:55
nice :) closing this then

**Closed as completed by someaddons** 2023-09-15 07:55 UTC
